"""Report export services: CSV, Excel (xlsx), and PDF.

Exports follow the DESIGN.md system for the visual language where feasible:
tabular-figure numerics, deep navy headings, and the indigo primary accent.
"""

from __future__ import annotations

import csv
import io
import re

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from app.models import Dataset
from app.schemas.analytics import SeriesPoint

PRIMARY = colors.HexColor("#533afd")
INK = colors.HexColor("#0d253d")
INK_MUTE = colors.HexColor("#64748d")
HAIRLINE = colors.HexColor("#e3e8ee")


def sanitize_filename(name: str) -> str:
    safe = re.sub(r"[^a-zA-Z0-9-_]+", "-", name).strip("-")
    return safe or "report"


def to_csv(dataset: Dataset, series: list[SeriesPoint]) -> io.BytesIO:
    buffer = io.StringIO()
    writer = csv.writer(buffer)
    writer.writerow(["dataset", dataset.name, "slug", dataset.slug])
    writer.writerow(["metric_type", dataset.metric_type, "unit", dataset.unit])
    writer.writerow([])
    writer.writerow(["timestamp", "value"])
    for point in series:
        writer.writerow([point.timestamp.isoformat(), point.value])
    return io.BytesIO(buffer.getvalue().encode("utf-8"))


def to_excel(dataset: Dataset, series: list[SeriesPoint]) -> io.BytesIO:
    from openpyxl import Workbook
    from openpyxl.styles import Font, PatternFill
    from openpyxl.utils import get_column_letter

    wb = Workbook()
    ws = wb.active
    ws.title = dataset.slug[:31]

    header_fill = PatternFill("solid", fgColor="1C1E54")
    header_font = Font(color="FFFFFF", bold=True, size=11)
    indigo_font = Font(color="533AFD", bold=True)

    ws.append([dataset.name])
    ws["A1"].font = indigo_font
    ws.append([f"{dataset.metric_type} · {dataset.unit} · {dataset.currency}"])
    ws.append([])
    ws.append(["Timestamp", "Value"])
    for cell in ws[4]:
        cell.fill = header_fill
        cell.font = header_font
    for point in series:
        ws.append([point.timestamp.isoformat(), point.value])

    ws.column_dimensions["A"].width = 28
    ws.column_dimensions["B"].width = 16
    for row in ws.iter_rows(min_row=5, min_col=2):
        for cell in row:
            cell.number_format = "#,##0.00"

    buffer = io.BytesIO()
    wb.save(buffer)
    buffer.seek(0)
    return buffer


def to_pdf(dataset: Dataset, series: list[SeriesPoint]) -> io.BytesIO:
    buffer = io.BytesIO()

    title_style = ParagraphStyle(
        name="Title", fontName="Helvetica", fontSize=18, leading=22,
        textColor=INK, spaceAfter=4,
    )
    sub_style = ParagraphStyle(
        name="Sub", fontName="Helvetica", fontSize=10, leading=13,
        textColor=INK_MUTE, spaceAfter=18,
    )
    cell_style = ParagraphStyle(
        name="Cell", fontName="Helvetica", fontSize=9, leading=11, textColor=INK,
    )
    header_style = ParagraphStyle(
        name="Head", fontName="Helvetica-Bold", fontSize=9, leading=11,
        textColor=colors.white,
    )

    doc = SimpleDocTemplate(
        buffer,
        pagesize=landscape(A4),
        rightMargin=0.6 * inch,
        leftMargin=0.6 * inch,
        topMargin=0.6 * inch,
        bottomMargin=0.6 * inch,
        title=f"{dataset.name} — {dataset.metric_type}",
    )

    rows = [[Paragraph("Timestamp", header_style), Paragraph("Value", header_style)]]
    for point in series:
        rows.append(
            [
                Paragraph(point.timestamp.isoformat(), cell_style),
                Paragraph(f"{point.value:,.2f}", cell_style),
            ]
        )

    table = Table(rows, colWidths=[4.2 * inch, 2.2 * inch], repeatRows=1)
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), PRIMARY),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("GRID", (0, 0), (-1, -1), 0.5, HAIRLINE),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f6f9fc")]),
                ("ALIGN", (1, 0), (1, -1), "RIGHT"),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ]
        )
    )

    story = [
        Paragraph(dataset.name, title_style),
        Paragraph(
            f"{dataset.metric_type} · {dataset.unit} · {dataset.currency} · "
            f"{len(series)} periods · generated by InferSight",
            sub_style,
        ),
        Spacer(1, 6),
        table,
    ]
    doc.build(story)
    buffer.seek(0)
    return buffer


def filename_for(dataset: Dataset, ext: str) -> str:
    return f"{sanitize_filename(dataset.slug)}-{ext}.{ext}"
